### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by dirkk0** [flipace/lovli.js#1]
Hi,

  the horizon link in the demo is wrong:
https://github.com/flipace/lovli.js/blob/master/source/client/components/App.js#L16
(page doesn't exist: https://github.com/rethinkdb/horizon )

Best,
  Dirk

**Comment by flipace** [comment]
Hi @dirkk0 the link is correct - the repository is private at the moment though, you can sign up for an invite on http://horizon.io/ :)
