### ISSUE TITLE
Hot reload causes blank page

### ISSUE THREAD

**Issue by mike-marcacci** [flipace/lovli.js#11]
Just cloned lovli.js, ran `npm i` and `npm start`; works great until a hot reload is attempted, after which a white page is displayed without any errors in the console. Refreshing the page fixes it.

**Comment by dmalik** [comment]
I'm having the same issue. Chrome 51 on Windows 10.

**Comment by flipace** [comment]
thanks! fixed with 64b8f090300245b9403061fec75ae29b348e8c09.
