### ISSUE TITLE
Provider from redux imported but not used

### ISSUE THREAD

**Issue by wandererfrog** [flipace/lovli.js#13]
In "source/client/containers/Root.js" there is an import of the Provider class but it is not used? Why is it there?

**Comment by flipace** [comment]
hi @icylabsDev it's there because i totally forgot to remove it after i replaced it with the horizon connector. sorry 'bout that.

**Comment by flipace** [comment]
fixed in 502c32a2b566f8ffb61ef94ff7577f6523fd45de

**Comment by wandererfrog** [comment]
=) I thought so, but wanted to be sure ^^ great job!

**Comment by ddaaggeett** [comment]
@flipace - I'm new to Horizon, and this question may be premature, but why was development steered away from using Redux? Also, this leads to my [main question](https://github.com/flipace/lovli.js/issues/23)...
